name = "sjmb-scraper"
main = "src/worker.js"
compatibility_date = "2025-01-01"

[triggers]
crons = ["*/10 * * * *"]

[[kv_namespaces]]
binding = "SEEN_POSTS_KV"
id = "9e883983a7ed49c2bedcf1737265bb9c"
